#!/usr/bin/env bash

#!/bin/sh

# Resolve the source path even if it's a symlink:
SOURCE="$0"

while [ -L "$SOURCE" ]; do
  DIR="$(cd -P -- "$(dirname -- "$SOURCE")" && pwd -P)"
  SOURCE="$(readlink "$SOURCE")"

  # If $SOURCE was a relative symlink, resolve it relative to the symlink directory
  case "$SOURCE" in
    /*) ;; # absolute path, do nothing
    *) SOURCE="$DIR/$SOURCE" ;;
  esac
done

BASE_DIR="$(cd -P -- "$(dirname -- "$SOURCE")" && pwd -P)"

# Finally run perpelxity-cli wrapper

$BASE_DIR/wrapper.py $1 "$2"
