#!/usr/bin/env bash

# Resolve the actual path of this script (following all symlinks)
SOURCE="${BASH_SOURCE[0]:-$0}"
while [ -h "$SOURCE" ]; do
  DIR="$(cd -P -- "$(dirname -- "$SOURCE")" && pwd -P)"
  SOURCE="$(readlink "$SOURCE")"
  # If SOURCE is relative, resolve it relative to the directory from above
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done
BASE_DIR="$(cd -P -- "$(dirname -- "$SOURCE")" && pwd -P)"

echo "Resolved BASE_DIR=$BASE_DIR"

python3 "$BASE_DIR/wrapper.py" "$@"
